# vim: set filetype=yaml:
---
cpus_per_dock: 1
max_docks: 1
rigidity: soft
morbidity: hard
cputhresh: 100

dock_condor_conf:
 condor_common_conf: /dev/null
 condor_worknode_conf: /dev/null
 condor_base_conf: /dev/null

parrot_wrapper_path: /dev/null

pilot_dock: plancton/slc6-wq:latest
pilot_privileged: True 

local_configs:
 cms_local_config: /dev/null
