# vim: set filetype=yaml:
---
###############################################################################
#      Plancton: a voluntary computing project.      email: mconcas@cern.ch   #
###############################################################################

##
# This configuration file is intended to be left as is. Every modification or
# edit might cause a deamon malfunction. Remember that to be a computing 
# volunteer means to share your spare resources to the community, not to
# renounce to use your PC. Be generous!  
##

##
# Resources constraints.
##
cpus_per_dock: 0.5     # the amount of CPU to share.
max_docks: ncpus - 1   # ncpus is the actual (physical + ht) core number.
rigidity: soft         # [soft|medium|hard]
morbidity: hard        # How often check container statuses.
cputhresh: 75          # 0-100% threshold to trigger container deletion.
 
##
# Condor configurations, files. 
# Please notice that in a std installation is likely you don't need to edit arguments below.
##
dock_condor_conf:
 condor_common_conf:   /opt/plancton/.plancton/conf/condor-configuration/10-common.config
 condor_worknode_conf: /opt/plancton/.plancton/conf/condor-configuration/00-worker.config
 condor_base_conf:     /opt/plancton/.plancton/conf/condor-configuration/condor_config

##
# Docks parameters 
##
pilot_entrypoint: /tmp/condor-centos6-worker-pilot
pilot_dock: mconcas/centos6-autobuild-container:latest
